# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/mohanrajmit/Image-Read/blob/master/NeualNetworks_pima.ipynb
"""

from keras.models import Sequential
from keras.layers import Dense
import numpy

import pandas as pd

!git clone https://github.com/mohanrajmit/Image-Read.git

df = pd.read_csv("/content/Image-Read/pima-indians-diabetes.csv",header=None)

df.tail()

df[df[8]==0]

df[df[8]==1]



# fix random seed for reproducibility
seed = 7
numpy.random.seed(seed)
# load pima indians dataset
dataset = numpy.loadtxt("/content/Image-Read/pima-indians-diabetes.csv", delimiter=",")
# split into input (X) and output (Y) variables
X = dataset[:,0:8]
Y = dataset[:,8]

"""#pima indian dataset

"""

# create model
model = Sequential()
model.add(Dense(12, input_dim=8,  activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(10, activation='tanh'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
# Compile model

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.summary()

# Fit the model
model.fit(X, Y, epochs=400, batch_size=40)

# evaluate the model
scores = model.evaluate(X, Y)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

